name: Conda

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-13]
        python-version: ["3.8", "3.10"]

    runs-on: ${{ matrix.platform }}

    # The setup-miniconda action needs this to activate miniconda
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - uses: actions/checkout@v4

      - name: Get conda
        uses: conda-incubator/setup-miniconda@v3.1.1
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Prepare
        run: conda install conda-build conda-verify

      - name: Install Eigen
        run: conda install -c conda-forge eigen

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Remove Git for Windows from PATH (Windows)
        if: runner.os == 'Windows'
        run: |
          echo "##[group]Fix PATH"
          echo "PATH before: $PATH"
          export PATH=$(echo "$PATH" | tr ':' '\n' | grep -v '/usr/bin' | paste -sd ':' -)
          echo "PATH after: $PATH"
          echo "##[endgroup]"
          conda build conda.recipe
      - name: Install build dependencies
        run: conda install pybind11
      

      - name: Build
        if: runner.os != 'Windows'
        run: conda build conda.recipe

      - name: Install
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ oilspillsim

      - name: Test
        run: python tests/test.py
